apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: grafana
    group: gpg
  name: grafana
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
        group: gpg
    spec:
      containers:
      - image: grafana/grafana:5.1.0
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always

