apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphite
    group: gpg
  name: graphite
spec:
  type: NodePort
  ports:
  - name: "9108"
    port: 9108
    targetPort: 9108
    nodePort: 30108
  - name: "9109"
    port: 9109
    targetPort: 9109
    nodePort: 30109
  selector:
    app: graphite

