{
 "title": "Spark Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_ID", "label": "App ID", "query": "label_values(app)" }
  ]
 },
 "panels": [
  {
   "title": "Processed Rows /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "app_ID",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "structured_streaming{app=\"$app_ID\", qty=\"processedRowsPerSecond\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Driver Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", app=\"$app_ID\", executor_id=\"driver\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Driver JVM Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id=\"driver\", app=\"$app_ID\",qty=\"used\"}",
     "legendFormat": "{{mem_type}}"
    }
   ]
  },
  {
   "title": "Executor Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", app=\"$app_ID\", executor_id!~\"driver\"} ",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Eden-Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", app=\"$app_ID\",qty=\"usage\", mem_type=\"PS-Eden-Space\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Old-Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", app=\"$app_ID\",qty=\"usage\", mem_type=\"PS-Old-Gen\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(executor_tasks{app=\"$app_ID\", qty!~\"maxPool_size\"}) by (qty)",
     "legendFormat": "{{qty}}"
    }
   ]
  }
 ]
}